# Generated by Django 3.2.25 on 2025-10-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='CNPJ',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='CPF',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(default='sem telefone', max_length=200),
        ),
    ]
