# Generated by Django 3.2.25 on 2025-10-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_api', '0002_auto_20251023_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='CNPJ',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
