# Generated by Django 3.2.25 on 2025-10-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_api', '0003_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='CNPJ',
            field=models.CharField(max_length=200),
        ),
    ]
